FROM ubuntu:18.04
MAINTAINER Sergio

ENV HOME /home
WORKDIR /home

COPY ./scripts/utils.sh .
COPY ./scripts/icarus.sh .
COPY ./scripts/tools.sh .
COPY ./scripts/ghdl.sh .

RUN apt-get -qq update 

RUN chmod 777 *.sh
RUN ./utils.sh
RUN ./icarus.sh
RUN ./tools.sh
RUN ./ghdl.sh
