FROM ubuntu:18.04
MAINTAINER Sergio

ENV HOME /home
WORKDIR /home

COPY ./scripts/utils.sh .
COPY ./scripts/ghdl.sh .
COPY ./scripts/verilator.sh .
COPY ./scripts/tools.sh .

RUN apt-get -qq update

RUN chmod 777 *.sh
RUN ./utils.sh
RUN ./ghdl.sh
RUN ./verilator.sh
RUN ./tools.sh
